export const imageMap = {
    'case.jpg': require('@/assets/images/case.jpg'),
    'cup.jpg': require('@/assets/images/cup.jpg'),
    'default.jpg': require('@/assets/images/default.jpg'),
    'house.jpg': require('@/assets/images/cottage.webp'),
    'plate.jpg': require('@/assets/images/plate.jpg'),

    'childcare.webp': require('@/assets/images/icons/expense/childcare.webp'),
    'clothing.webp': require('@/assets/images/icons/expense/clothing.webp'),
    'dining.webp': require('@/assets/images/icons/expense/dining.webp'),
    'education.webp': require('@/assets/images/icons/expense/education.webp'),
    'fitness.webp': require('@/assets/images/icons/expense/fitness.webp'),
    'groceries.webp': require('@/assets/images/icons/expense/groceries.webp'),
    'health.webp': require('@/assets/images/icons/expense/health.webp'),
    'home.webp': require('@/assets/images/icons/expense/home.webp'),
    'house.webp': require('@/assets/images/icons/expense/house.webp'),
    'insurance.webp': require('@/assets/images/icons/expense/insurance.webp'),
    'internet.webp': require('@/assets/images/icons/expense/internet.webp'),
    'phone.webp': require('@/assets/images/icons/expense/phone.webp'),
    'saving.webp': require('@/assets/images/icons/expense/saving.webp'),
    'transportation.webp': require('@/assets/images/icons/expense/transportation.webp'),
    'travel.webp': require('@/assets/images/icons/expense/travel.webp'),
    'utilities.webp': require('@/assets/images/icons/expense/utilities.webp'),

    'freelance.webp': require('@/assets/images/icons/income/freelance.webp'),
    'gifts.webp': require('@/assets/images/icons/income/gifts.webp'),
    'investment.webp': require('@/assets/images/icons/income/investment.webp'),
    'present.webp': require('@/assets/images/icons/income/present.webp'),
    'rental.webp': require('@/assets/images/icons/income/rental.webp'),
    'salary.webp': require('@/assets/images/icons/income/salary.webp'),

};